name: Repository and paper info
on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'URL of the repository where the paper file is'
        required: true
      branch:
        description: 'Git branch with the paper file'
        required: false
        default: ""
      issue_id:
        description: 'The issue number of the submission to post the results'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  GH_REPO: openjournals/joss-reviews
jobs:
  run-analysis:
    name: ${{ format('Repository and paper analysis for issue {0}', github.event.inputs.issue_id) }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository and paper analysis
        uses: openjournals/gh-action-repo-checks@main
        with:
          repository_url: ${{ github.event.inputs.repository_url }}
          branch: ${{ github.event.inputs.branch }}
          issue_id: ${{ github.event.inputs.issue_id }}
