name: Retract paper
on:
  workflow_dispatch:
    inputs:
      issue_id:
        description: 'The issue number of the retracted paper review'
        required: true
      retraction_notice_url:
        description: 'URL for the markdown file of the retraction notice'
        required: true
      mode:
        description: Set the compiled retraction notice as a draft or as a final published paper. Posible values are 'draft' or 'final'.
        required: false
        default: draft
jobs:
  retraction-notice:
    name: ${{ format('Retracting paper in issue {0}', github.event.inputs.issue_id) }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate retraction notice
        id: generate-retraction
        uses: xuanxu/retraction-action@main
        with:
          retraction_notice_url: ${{ github.event.inputs.retraction_notice_url }}
          issue_id: ${{ github.event.inputs.issue_id }}
          journal: joss
          papers_repo: openjournals/joss-papers
          papers_repo_main_branch: master
          branch_prefix: joss
          github_bot_token: ${{ secrets.BOT_TOKEN }}
          journal_secret: ${{ secrets.JOSS_SECRET }}
          crossref_username: ${{ secrets.CROSSREF_USERNAME }}
          crossref_password: ${{ secrets.CROSSREF_PASSWORD }}
          mode: ${{ github.event.inputs.mode }}
